/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextToSignRouteImport } from './routes/text-to-sign'
import { Route as SignToTextRouteImport } from './routes/sign-to-text'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CommunicationBoardRouteImport } from './routes/communication-board'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as IndexRouteImport } from './routes/index'

const TextToSignRoute = TextToSignRouteImport.update({
  id: '/text-to-sign',
  path: '/text-to-sign',
  getParentRoute: () => rootRouteImport,
} as any)
const SignToTextRoute = SignToTextRouteImport.update({
  id: '/sign-to-text',
  path: '/sign-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationBoardRoute = CommunicationBoardRouteImport.update({
  id: '/communication-board',
  path: '/communication-board',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/communication-board': typeof CommunicationBoardRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-to-text': typeof SignToTextRoute
  '/text-to-sign': typeof TextToSignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/communication-board': typeof CommunicationBoardRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-to-text': typeof SignToTextRoute
  '/text-to-sign': typeof TextToSignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caregiver': typeof CaregiverRoute
  '/communication-board': typeof CommunicationBoardRoute
  '/emergency': typeof EmergencyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sign-to-text': typeof SignToTextRoute
  '/text-to-sign': typeof TextToSignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caregiver'
    | '/communication-board'
    | '/emergency'
    | '/profile'
    | '/settings'
    | '/sign-to-text'
    | '/text-to-sign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caregiver'
    | '/communication-board'
    | '/emergency'
    | '/profile'
    | '/settings'
    | '/sign-to-text'
    | '/text-to-sign'
  id:
    | '__root__'
    | '/'
    | '/caregiver'
    | '/communication-board'
    | '/emergency'
    | '/profile'
    | '/settings'
    | '/sign-to-text'
    | '/text-to-sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaregiverRoute: typeof CaregiverRoute
  CommunicationBoardRoute: typeof CommunicationBoardRoute
  EmergencyRoute: typeof EmergencyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignToTextRoute: typeof SignToTextRoute
  TextToSignRoute: typeof TextToSignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-to-sign': {
      id: '/text-to-sign'
      path: '/text-to-sign'
      fullPath: '/text-to-sign'
      preLoaderRoute: typeof TextToSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-to-text': {
      id: '/sign-to-text'
      path: '/sign-to-text'
      fullPath: '/sign-to-text'
      preLoaderRoute: typeof SignToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-board': {
      id: '/communication-board'
      path: '/communication-board'
      fullPath: '/communication-board'
      preLoaderRoute: typeof CommunicationBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaregiverRoute: CaregiverRoute,
  CommunicationBoardRoute: CommunicationBoardRoute,
  EmergencyRoute: EmergencyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignToTextRoute: SignToTextRoute,
  TextToSignRoute: TextToSignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
